version: '3.8'
services:
  server:
    build: ./server
    hostname: backend
    ports:
      - '8000:8000'
  
  client:
    build: ./client
    hostname: frontend
    ports:
      - '3000:80'
    depends_on:
      - server